import { Api } from './src/index';

async function test() {
    const api = new Api({email: '', password: ''});
    const wikifolio = api.wikifolio('')

    await wikifolio.details();

    console.log('user', wikifolio.user)
    console.log('id', wikifolio.id)
    console.log('symbol', wikifolio.symbol)
    console.log('wikifolioUrl', wikifolio.wikifolioUrl)
    console.log('isin', wikifolio.isin)
    console.log('wkn', wikifolio.wkn)
    console.log('createdAt', wikifolio.createdAt)
    console.log('publishedAt', wikifolio.publishedAt)
    console.log('status', wikifolio.status)
    console.log('status', wikifolio.status)
    console.log('tags', wikifolio.tags)
    console.log('capital', wikifolio.capital)
    console.log('title', wikifolio.title)
    console.log('tradeidea', wikifolio.tradeidea)
    console.log('highWatermark', wikifolio.highWatermark)
    console.log('indexLevel', wikifolio.indexLevel)
    console.log('fee', wikifolio.fee)
    console.log('liquidation', wikifolio.liquidation)
    console.log('tradingVolume', wikifolio.tradingVolume)
    console.log('decisionMaking', wikifolio.decisionMaking)
    console.log('chartImgUrl', wikifolio.chartImgUrl)
    console.log('investable', wikifolio.investable)
    console.log('containsLeverageProducts', wikifolio.containsLeverageProducts)
    console.log('realMoney', wikifolio.realMoney)
    console.log('isWatchlisted', wikifolio.isWatchlisted)
    console.log('name', wikifolio.name)
    console.log('isOwned', wikifolio.isOwned)
    console.log('rank', wikifolio.rank)
    console.log('isSuper', wikifolio.isSuper)
    console.log('isChallenge', wikifolio.isChallenge)
    console.log('isClosed', wikifolio.isClosed)
    console.log('sharperatio', wikifolio.sharperatio)
    console.log('perf12m', wikifolio.perf12m)
    console.log('perf6m', wikifolio.perf6m)
    console.log('perf3m', wikifolio.perf3m)
    console.log('perf1m', wikifolio.perf1m)
    console.log('perfever', wikifolio.perfever)
    console.log('perfemission', wikifolio.perfemission)
    console.log('perfannually', wikifolio.perfannually)
    console.log('perfytd', wikifolio.perfytd)
    console.log('esgScore', wikifolio.esgScore)
    console.log('maxdraw', wikifolio.maxdraw)
    console.log('aum', wikifolio.aum)
    console.log('risk', wikifolio.risk)
    console.log('perftoday', wikifolio.perftoday)
    console.log('perfintra', wikifolio.perfintra)
    console.log('perf52weekHigh', wikifolio.perf52weekHigh)
    console.log('ask', wikifolio.ask)
    console.log('bid', wikifolio.bid)
    console.log('quantityLimitBid', wikifolio.quantityLimitBid)
    console.log('quantityLimitAsk', wikifolio.quantityLimitAsk)
    console.log('priceCalculatedAt', wikifolio.priceCalculatedAt)
    console.log('priceValidUntil', wikifolio.priceValidUntil)
    console.log('midPrice', wikifolio.midPrice)
    console.log('showMidPrice', wikifolio.showMidPrice)
    console.log('isCurrencyConverted', wikifolio.isCurrencyConverted)
    console.log('isTicking', wikifolio.isTicking)
    console.log('isNotificationSet', wikifolio.isNotificationSet)
    console.log('buyint', wikifolio.buyint)
    console.log('bought30d', wikifolio.bought30d)
    console.log('perf36m', wikifolio.perf36m)
    console.log('perf60m', wikifolio.perf60m)
    console.log('perf52week', wikifolio.perf52week)
    console.log('tradevol30d', wikifolio.tradevol30d)
    console.log('perfbuy', wikifolio.perfbuy)
    console.log('comments', wikifolio.comments)
    console.log('category', wikifolio.category)
}

test()
